owner: a1um1
repo: status

sites:
  - name: m3ow.xyz
    url: https://m3ow.xyz
    method: GET

status-website:
  name: Status
  introTitle: "**m3ow.xyz** Uptime Monitor"
  cname: a1um1.github.io
  baseUrl: /status
  introMessage: This status page is automatically updated every 5 minutes by Upptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/a1um1/status

notifications:
  - type: discord
